### ISSUE TITLE
Failed to create IBM Cloud VPC Block CSI Driver on Single Node OpenShift in IBM Cloud VPC

### ISSUE THREAD

**Issue by aazraq** [kubernetes-sigs/ibm-vpc-block-csi-driver#155]
Environment details:
Single Node OpenShift cluster running on IBM Cloud VPC VSI.
OpenShift: 4.12

Problem Description:
I tried to follow the instructions here, and built the image from the master branch and pushed it to IBM Cloud Container Registry. However this command failed

`bash deploy/kubernetes/driver/kubernetes/deploy-vpc-block-driver.sh stage`

with this issue
```
This will install 'stage' version of vpc csi driver!
darwin22
Error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
error: no objects passed to apply
```

I contacted @ambiknai who was very helpful and very generous with her time and troubleshooted the issue with me, and gave me manual yaml files which progressed the CSI driver creation, but still it's failing with the below issue. 

Attached are the logs.
[csi-provisioner.log](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/files/11895132/csi-provisioner.log)
[ibm-vpc-block-csi-controller.log](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/files/11895137/ibm-vpc-block-csi-controller.log)

**Comment by ambiknai** [comment]
Thanks @aazraq  for opening this issue.

Adding few findings

Point of failure - https://github.com/IBM/ibm-csi-common/blob/master/pkg/metadata/metadata.go#L89-L97

Added labels manually to bring driver pods up

`ibm-cloud.kubernetes.io/machine-type]: upi`

Pods came to healthy state.

We see errors in PVC

```
 Warning ProvisioningFailed  43s (x7 over 106s)  vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-6c879448cd-9r25v_0ed93c94-66e5-4cab-9a88-fb4b364f0cd4 failed to provision volume with StorageClass "ibmc-vpc-block-5iops-tier": error generating accessibility requirements: no available topology found
 ```

**Comment by ambiknai** [comment]
1. After adding above label, also added 
` ibm-cloud.kubernetes.io/vpc-instance-id: 0787_d639182e-44cc-4ab7-bbfc-8f69e9606664`
2. Restarted all pods

node-pod was still in CrashLoopBackoff

node-driver-registart is unable to connect to socket


I did `strace`

1. In the worker node terminal, you do `ps -aux| grep “node-driver-registrar”
2. Get the pid
3. and then you do strace -p $( pidof node-driver-registrar)



```
clock_gettime(CLOCK_MONOTONIC, {tv_sec=241466, tv_nsec=927945202}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1688114739, tv_nsec=31720390}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=241466, tv_nsec=929814102}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=241466, tv_nsec=930230648}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=241466, tv_nsec=930500755}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1688114739, tv_nsec=34867350}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=241466, tv_nsec=931948439}) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/csi/csi.sock"}, 16) = -1 EACCES (Permission denied)
close(3)                                = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1688114739, tv_nsec=37431080}) = 0
```

It has some permission issues

**Comment by jeffnowicki** [comment]
Suggest following up on this reported issue which looks like the problem you are hitting: https://github.com/kubernetes-csi/node-driver-registrar/issues/36#issuecomment-475846964

**Comment by jsafrane** [comment]
This smells like SELinux. In RHEL, we traditionally run both CSI driver and driver registrar as privileged containers, so both can access the host (`/var/lib/kubelet/*`). Even a pod that runs as root can do very little on the host because of SELinux, unless it's privileged.

Running the registrar as `privileged: true` is not necessary since https://github.com/kubernetes/kubernetes/pull/73241, Kubernetes 1.15?), even an unprivileged pod that runs as root can write to `/var/lib/kubelet/plugins` and `/var/lib/kubelet/plugins_registry`.

I don't know what prevents the registrar to access `/csi/csi.sock`.
* What SELinux context does the driver socket have on the host?
`ls -aZ /var/lib/kubelet/plugins` and `ls -aZ /var/lib/kubelet/plugins_registry` could tell you. It should be `system_u:object_r:container_file_t:s0` in both cases
* How the node-driver-registrar runs? `ps -auxZ | grep registrar`. A privileged container should have `system_u:system_r:spc_t:s0`, allowing the registrar accessing anything on the host. A non-privileged registrar should have something like `system_u:system_r:container_t:s0:c101,c943`, allowing the registrar to access anything with `system_u:object_r:container_file_t:s0`, but nothing else on the host.

You see anything else, who changed the contexts and why?

**Comment by ambiknai** [comment]
@aazraq  Could you share above command O/P from your setup.

**Comment by ambiknai** [comment]
@jsafrane  Another team reported similar issue where node-driver pods were restarting.

I checked all commands which you mentioned in above comment.

```
[root@test-ckehqph20ccgdlvbd0j0-dmhyper71-default-00000d87 /]# ps -aux| grep "node-driver-registrar"
root       5805  0.0  0.1 725532 23580 ?        Ssl  09:45   0:11 /csi-node-driver-registrar --v=5 --csi-address=/csi/csi.sock --kubelet-registration-path=/var/data/kubelet/csi-plugins/vpc.block.csi.ibm.io/csi.sock
root      34910  0.0  0.0   3884  2040 pts/0    S+   14:13   0:00 grep --color=auto node-driver-registrar
[root@test-ckehqph20ccgdlvbd0j0-dmhyper71-default-00000d87 /]# strace -p 5805
strace: Process 5805 attached
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
nanosleep({tv_sec=0, tv_nsec=3000}, NULL) = 0
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
nanosleep({tv_sec=0, tv_nsec=3000}, NULL) = 0
futex(0xc00005c548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
nanosleep({tv_sec=0, tv_nsec=3000}, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
nanosleep({tv_sec=0, tv_nsec=3000}, NULL) = 0
write(6, "\0", 1)                       = 1
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
epoll_pwait(4, [], 128, 740, NULL, 16478342516424) = 0
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005c548, FUTEX_WAKE_PRIVATE, 1) = 1
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/csi/csi.sock"}, 16) = -1 EACCES (Permission denied)
close(3)                                = 0
futex(0xc00005c948, FUTEX_WAKE_PRIVATE, 1) = 1
write(6, "\0", 1)                       = 1
nanosleep({tv_sec=0, tv_nsec=3000}, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
nanosleep({tv_sec=0, tv_nsec=3000}, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
epoll_pwait(4, [{events=EPOLLIN, data={u32=17034584, u64=17034584}}], 128, 3660, NULL, 16487601007594) = 1
read(5, "\0", 16)                       = 1
epoll_pwait(4, [], 128, 984, NULL, 16484926956312) = 0
futex(0xc00005c948, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005c548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005c548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005c948, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
epoll_pwait(4, [{events=EPOLLIN, data={u32=17034584, u64=17034584}}], 128, 1630, NULL, 16487601007594) = 1
read(5, "\0", 16)                       = 1
epoll_pwait(4, [], 128, 958, NULL, 16486934167865) = 0
futex(0xc0003f8148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005c948, FUTEX_WAKE_PRIVATE, 1) = 1
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/csi/csi.sock"}, 16) = -1 EACCES (Permission denied)
close(3)                                = 0
futex(0xc00005c948, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005c548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x100f4a8, FUTEX_WAIT_PRIVATE, 0, NULL^Cstrace: Process 5805 detached
 <detached ...>

[root@test-ckehqph20ccgdlvbd0j0-dmhyper71-default-00000d87 /]# ls -aZ /var/lib/kubelet/plugins
   system_u:object_r:container_file_t:s0 .  system_u:object_r:container_var_lib_t:s0 ..
[root@test-ckehqph20ccgdlvbd0j0-dmhyper71-default-00000d87 /]# ls -aZ /var/lib/kubelet/plugins_registry
   system_u:object_r:container_file_t:s0 .  system_u:object_r:container_var_lib_t:s0 ..
[root@test-ckehqph20ccgdlvbd0j0-dmhyper71-default-00000d87 /]# ps -auxZ | grep registrar
system_u:system_r:container_runtime_t:s0 root 5789 0.0  0.0 8304  1992 ?        Ss   09:45   0:00 /usr/bin/conmon -b /var/data/crioruntimestorage/overlay-containers/d817c068ed9c86bea0d3024903e707e2c63ad11d4456aebd22ab0f4e394214c8/userdata -c d817c068ed9c86bea0d3024903e707e2c63ad11d4456aebd22ab0f4e394214c8 --exit-dir /var/run/crio/exits -l /var/log/pods/kube-system_ibm-vpc-block-csi-node-tz5m4_222f01fb-d7cd-4075-8fba-120ff0b32ccd/csi-driver-registrar/0.log --log-level info -n k8s_csi-driver-registrar_ibm-vpc-block-csi-node-tz5m4_kube-system_222f01fb-d7cd-4075-8fba-120ff0b32ccd_0 -P /var/data/crioruntimestorage/overlay-containers/d817c068ed9c86bea0d3024903e707e2c63ad11d4456aebd22ab0f4e394214c8/userdata/conmon-pidfile -p /var/data/crioruntimestorage/overlay-containers/d817c068ed9c86bea0d3024903e707e2c63ad11d4456aebd22ab0f4e394214c8/userdata/pidfile --persist-dir /var/data/criorootstorage/overlay-containers/d817c068ed9c86bea0d3024903e707e2c63ad11d4456aebd22ab0f4e394214c8/userdata -r /usr/bin/runc --runtime-arg --root=/run/runc --socket-dir-path /var/run/crio --syslog -u d817c068ed9c86bea0d3024903e707e2c63ad11d4456aebd22ab0f4e394214c8 -s
system_u:system_r:container_t:s0:c138,c358 root 5805 0.0  0.1 725532 23592 ?    Ssl  09:45   0:11 /csi-node-driver-registrar --v=5 --csi-address=/csi/csi.sock --kubelet-registration-path=/var/data/kubelet/csi-plugins/vpc.block.csi.ibm.io/csi.sock
system_u:system_r:spc_t:s0      root      38152  0.0  0.0   3876  2092 pts/0    S+   14:15   0:00 grep --color=auto registrar
[root@test-ckehqph20ccgdlvbd0j0-dmhyper71-default-00000d87 /]# 
```


```
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REGISTRATION_SOCK)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REGISTRATION_SOCK
          value: /var/data/kubelet/csi-plugins/vpc.block.csi.ibm.io/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: icr.io/ext/sig-storage/csi-node-driver-registrar:v2.7.0
        imagePullPolicy: Always
        name: csi-driver-registrar
        resources:
          limits:
            cpu: 40m
            memory: 80Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          privileged: false
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --v=5
        - --endpoint=unix:/csi/csi.sock
        - --sidecarEndpoint=$(SIDECAREP)
        env:
        - name: SIDECAREP
          value: /sidecardir/provider.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: ibm-vpc-block-csi-configmap
        image: us.icr.io/armada-master/ibm-vpc-block-csi-driver:v5.1.13
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: iks-vpc-block-node-driver
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        resources:
          limits:
            cpu: 120m
            memory: 300Mi
          requests:
            cpu: 30m
            memory: 75Mi
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sidecardir
          name: secret-sidecar-sock-dir
        - mountPath: /var/data/kubelet
          mountPropagation: Bidirectional
          name: kubelet-data-dir
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-lib-dir
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /dev
          name: device-dir
        - mountPath: /etc/udev
          name: etcudevpath
        - mountPath: /run/udev
          name: runudevpath
        - mountPath: /lib/udev
          name: libudevpath
        - mountPath: /sys
          name: syspath
        - mountPath: /etc/storage_ibmc
          name: customer-auth
          readOnly: true
        - mountPath: /etc/storage_ibmc/cluster_info
          name: cluster-info
          readOnly: true
      - args:
        - --csi-address=/csi/csi.sock
        image: icr.io/ext/sig-storage/livenessprobe:v2.9.0
        imagePullPolicy: IfNotPresent
        name: liveness-probe
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 5m
            memory: 10Mi
        securityContext:
          privileged: false
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      - args:
        - --endpoint=$(ENDPOINT)
        env:
        - name: ENDPOINT
          value: unix:/sidecardir/provider.sock
        - name: TOKEN_EXPIRY_DIFF
          value: 20m
        - name: PROFILE_CAPACITY
          value: "1"
        image: icr.io/obs/armada-storage-secret:v1.2.26
        imagePullPolicy: Always
        name: storage-secret-sidecar
        resources:
          limits:
            cpu: 40m
            memory: 80Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sidecardir
          name: secret-sidecar-sock-dir
        - mountPath: /var/run/secrets/tokens
          name: vault-token
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ibm-vpc-block-node-sa
      serviceAccountName: ibm-vpc-block-node-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - name: vault-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 600
              path: vault-token
      - emptyDir: {}
        name: secret-sidecar-sock-dir
      - hostPath:
          path: /var/data/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/data/kubelet
          type: Directory
        name: kubelet-data-dir
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-lib-dir
      - hostPath:
          path: /var/data/kubelet/csi-plugins/vpc.block.csi.ibm.io/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
      - hostPath:
          path: /etc/udev
          type: Directory
        name: etcudevpath
      - hostPath:
          path: /run/udev
          type: Directory
        name: runudevpath
      - hostPath:
          path: /lib/udev
          type: Directory
        name: libudevpath
      - hostPath:
          path: /sys
          type: Directory
        name: syspath
      - name: customer-auth
        secret:
          defaultMode: 420
          secretName: storage-secret-store
      - configMap:
          defaultMode: 420
          name: cluster-info
        name: cluster-info
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

```

Do you see any gap here @jsafrane
